language: python
python:
  - "3.6"
cache: pip
install:
  - pip install -e .
  - pip install httpretty
env:
  - TEST_DIR = "./test/1_link/"
before_script:
  - cd $TEST_DIR
script:
  - python ./link_test.py
