language: python
python:
  - "3.6"
cache: pip
install:
  - pip install -e .
  - pip install httpretty
script:
  - echo $TRAVIS_BUILD_DIR/tests/1_link/test.py
  - $TRAVIS_BUILD_DIR/tests/1_link/test.py
