language: python
python:
  - "3.6"
cache: pip
install:
  - pip install -e .
  - pip install httpretty
env:
  - TEST_DIR = /factory_pkg/tests/1_link
  - TEST_DIR = /factory_pkg/tests/2_relations
before-script:
  - cd $TRAVIS_BUILD_DIR
script:
  - cd $TEST_DIR && ls
