language: python
python:
  - "3.6"
cache: pip
install:
  - pip install -e .
  - pip install httpretty
env:
  #TEST_DIR = /tests/1_link/
  #TEST_DIR = /tests/2_relations/
script:
  - echo $TRAVIS_BUILD_DIR/tests/1_link/test.py
  - python $TRAVIS_BUILD_DIR/tests/1_link/test.py
